development:
  adapter: mysql2
  encoding: utf8
  database: google-exploiter
  pool: 5
  username: root
  password: '1234'
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  database: google-exploiter-test
  pool: 5
  username: root
  password: '1234'
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  database: google-exploiter
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock